services:
  app:
    container_name: ai-impact-visualization-app
    build: .
    env_file: .env
    ports:
      - "${SERVER__PORT}:${SERVER__PORT}"
    volumes:
      - ./app:/project/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: ai-impact-visualization-db
    image: postgres:16.8-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES__USER} -d ${POSTGRES__DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_DB: ${POSTGRES__DB}
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    ports:
      - "${POSTGRES__PORT}:${POSTGRES__PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
