"""Remove index

Revision ID: 995b54084ca8
Revises: 40c1558f0359
Create Date: 2025-03-24 08:26:18.259688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995b54084ca8'
down_revision: Union[str, None] = '40c1558f0359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commits_jira_issue_id', table_name='commits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_commits_jira_issue_id', 'commits', ['jira_issue_id'], unique=False)
    # ### end Alembic commands ###
